CREATE TABLE mail_api (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    target_from VARCHAR(255) NOT NULL,
    enable_flag TINYINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
