name: cloud-concierge CI

on:
  pull_request:
    paths:
      - .github/workflows/cloud-concierge-ci.yaml
      - 'cloud-concierge/**.js'
      - 'cloud-concierge/**.json'

jobs:
  cloud-concierge-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloud-concierge/functions

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: Cache node_modules dev packages
      uses: actions/cache@v4
      with:
        path: ~/node_modules
        key: ${{ runner.os }}-cloud-concierge-node-dev-${{ hashFiles('cloud-concierge/functions/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cloud-concierge-node-dev-

    - name: Check lint
      run: npm run lint
