name: cloud-concierge CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  cloud-concierge-test:
    name: cloud-concierge-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloud-concierge/functions

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Detect cloud-concierge changes
      id: filter
      uses: dorny/paths-filter@v4
      with:
        filters: |
          should-verify-cloud-concierge:
            - 'cloud-concierge/**'
            - '.github/workflows/cloud-concierge-ci.yaml'
            - '.github/workflows/cloud-concierge-deploy.yaml'

    - name: Setup Node.js
      if: steps.filter.outputs.should-verify-cloud-concierge == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: npm install
      if: steps.filter.outputs.should-verify-cloud-concierge == 'true'
      run: npm install

    - name: Cache node_modules dev packages
      if: steps.filter.outputs.should-verify-cloud-concierge == 'true'
      uses: actions/cache@v6
      with:
        path: ~/node_modules
        key: ${{ runner.os }}-cloud-concierge-node-dev-${{ hashFiles('cloud-concierge/functions/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cloud-concierge-node-dev-

    - name: Check lint
      if: steps.filter.outputs.should-verify-cloud-concierge == 'true'
      run: npm run lint
